#!/bin/bash
#SBATCH --mail-type="END,FAIL"
#SBATCH --mail-user=sophhuebler@gmail.com
#SBATCH --nodes=1
#SBATCH --ntasks=1

# NOTE: account/partition/array/time/mem are set from start_sim.R 
# SBATCH --account=guo
# SBATCH --partition=lonepeak-shared
# SBATCH --time=2:00:00
# SBATCH --mem-per-cpu=5000
# SBATCH --cpus-per-task=1

set -euo pipefail

# ---- Modules ----
module purge
module load R/4.4.2

# ---- Set up project root ----
PROJECT_ROOT="$HOME/Documents/SSL/Manuscript-BH_Additive_Cox"


# ---- Paths from --export  ----
mkdir -p "$resPath" "$scalePath" "$logPath"

# ---- Project root (so .Rprofile can auto-activate renv) ----
cd "$PROJECT_ROOT"
  


# ---- Run your R pipeline ----
Rscript Sim/Code/main.R \
  --n_train ${n_train} \
  --p ${p} \
  --rho ${rho} \
  --pi_cns ${pi_cns} \
  --resPath "${resPath}" \
  --scalePath "${scalePath}" \
  > "${logPath}/task_${SLURM_ARRAY_TASK_ID:-1}.Rout" 2>&1
